[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "photomaker"
version = "1.0.1"
description = "PhotoMaker: Customizing Realistic Human Photos via Stacked ID Embedding"
authors = ["TencentARC <to@be.entered>"]
license = "Apache-2.0" # Apache Software License

[[tool.poetry.source]]
name = "photomaker"
path = "photomaker"

[tool.poetry.dependencies]
python = ">=3.9,<3.11"

[tool.poetry.dev-dependencies]